# Generated by Django 2.0.2 on 2018-03-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsrc', '0004_profile_pending_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
