# Generated by Django 2.0.2 on 2018-03-02 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsrc', '0005_tasksubmission_accepted_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='review_submission_level',
        ),
    ]
