# Generated by Django 2.0.2 on 2018-03-03 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsrc', '0006_remove_userpreferences_review_submission_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprivacysettings',
            name='allow_search_level',
        ),
    ]
