# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsrc', '0002_auto_20170715_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='message',
        ),
    ]
